* More Fieldstones 2010
  :PROPERTIES:
  :CUSTOM_ID: more-fieldstones-2010
  :END:

[[./index.html][Home]]

** Data
   :PROPERTIES:
   :CUSTOM_ID: data
   :END:

Fri, 01 Jan 2010

If they do that with marks and grades, should they be trusted with experimental data?---Harry Erwin, PhD

** Research
   :PROPERTIES:
   :CUSTOM_ID: research
   :END:

Tue, 05 Jan 2010

If academic research is not devoted to finding the truth, it is a form of propaganda, and not necessarily to be preferred to other forms, much cheaper and perhaps more persuasive.---Conrad Russell (Academic Freedom. London: Routledge. 1993)

** Trust
   :PROPERTIES:
   :CUSTOM_ID: trust
   :END:

Wed, 20 Jan 2010

It is to me a new and consolatory proof that wherever the people are well-informed they can be trusted with their own government; that whenever things get so far wrong as to attract their notice, they may be relied on to set them to rights.---Thomas Jefferson to Richard Price, January 8, 1789

** Commas
   :PROPERTIES:
   :CUSTOM_ID: commas
   :END:

Fri, 29 Jan 2010

The older I grow, the less important the comma becomes. Let the reader catch his own breath.---Elizabeth Clarkson Zwart

** Sex and Science
   :PROPERTIES:
   :CUSTOM_ID: sex-and-science
   :END:

Fri, 29 Jan 2010

Science is a lot like sex. Sometimes something useful comes of it, but that's not the reason we're doing it.---Richard Feynman

** Habit
   :PROPERTIES:
   :CUSTOM_ID: habit
   :END:

Fri, 05 Feb 2010

We are what we repeatedly do. Excellence, then, is not an act, it's a habit.---Aristotle

** Improvisation
   :PROPERTIES:
   :CUSTOM_ID: improvisation
   :END:

Tue, 09 Feb 2010

Great improvisers are like priests. They are thinking only of their God.---Stéphane Grappelli

** Expertise
   :PROPERTIES:
   :CUSTOM_ID: expertise
   :END:

Thu, 11 Mar 2010

Nobody is an expert on the future.---Matt Linderman

** Smarts
   :PROPERTIES:
   :CUSTOM_ID: smarts
   :END:

Thu, 25 Mar 2010

You're not smart enough to tell me how to live.---Kathy Shaidle

** Understanding
   :PROPERTIES:
   :CUSTOM_ID: understanding
   :END:

Mon, 19 Apr 2010

It is difficult to get a man to understand something when his job depends on not understanding it.---Upton Sinclair

** Reality
   :PROPERTIES:
   :CUSTOM_ID: reality
   :END:

Fri, 30 Apr 2010

For a successful technology, reality must take precedence over public relations, for Nature cannot be fooled.---Richard Feynman

** Outrage
   :PROPERTIES:
   :CUSTOM_ID: outrage
   :END:

Tue, 11 May 2010

It is not more objective to narrate an outrage calmly.---James Chastek

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd
   :END:

Thu, 13 May 2010

If you don't read the newspaper, you are uninformed. If you do read the newspaper, you are misinformed.---Mark Twain

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-1
   :END:

Tue, 01 Jun 2010

You can safely assume that you've created God in your own image when it turns out that God hates all the same people you do.---Anne Lamott (Traveling Mercies, credited to "my priest friend Tom")

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-2
   :END:

Fri, 09 Jul 2010

All attacks on science are ultimately an attack on freedom. All attacks on religion are ultimately an attack on mind.---Robert W. Godwin

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-3
   :END:

Wed, 14 Jul 2010

We are as gods, and might as well get good at it.---The Whole Earth Catalog (1968)

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-4
   :END:

Wed, 28 Jul 2010

Science is the belief in the ignorance of experts.---Richard Feynman

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-5
   :END:

Fri, 30 Jul 2010

If there were no God, there would be no atheists.---Gilbert K. Chesterton

** Giving and Forgiving
   :PROPERTIES:
   :CUSTOM_ID: giving-and-forgiving
   :END:

Tue, 12 Oct 2010

If you have ill will toward any, if you are prejudiced against any, if you have accused any even in your silent thought, of injustice, or if you have criticised any one, sit down alone at night before retiring and mentally ask him to forgive you. Calling him by name, silently confess to him what you have done, and ask his forgiveness, telling him as you do the others, over and over again, that you love him, and are sure there is nothing but God's perfect Love between you. Never retire until you have thus definitely "cleaned up the slate" between yourself and every other human being, having definitely forgiven---given love for---every one. Keep at this until all the tightened cords which have been cutting off the free flow of God's love and life through you are loosened; until a habit of forgiving is established within you.---H. Emilie Cady /God a Present Help/

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-6
   :END:

Wed, 20 Oct 2010

Every atom of fear, or condemnation, or criticism, that we carry in our hearts, no matter for whom it may be, is a wall between ourselves and God.---Emmet Fox

** TOTD
   :PROPERTIES:
   :CUSTOM_ID: totd-7
   :END:

Fri, 29 Oct 2010

Being intelligent is not a felony, but most societies evaluate it as at least a misdemeanor.---Robert A. Heinlein

** Testimony
   :PROPERTIES:
   :CUSTOM_ID: testimony
   :END:

Mon, 08 Nov 2010

It isn't irrational to accept the testimony of eyewitnesses to miracles.---Antonin Scalia

** Time
   :PROPERTIES:
   :CUSTOM_ID: time
   :END:

Wed, 10 Nov 2010

It is only in appearance that time is a river. It is rather a vast landscape and it is the eye of the beholder that moves.---Thornton Wilder (The Eighth Day)

** Superstition
   :PROPERTIES:
   :CUSTOM_ID: superstition
   :END:

Sun, 12 Dec 2010

We must do our best to see life as it really is and not as modern superstition interprets it.---Lewis Maclachlan

** Science
   :PROPERTIES:
   :CUSTOM_ID: science
   :END:

Sun, 12 Dec 2010

We approach the subject (prayer) in a spirit of scientific enquiry. The question to be asked is not what according to our theology God ought to do, but what He actually does.---Lewis Maclachlan

** Belief
   :PROPERTIES:
   :CUSTOM_ID: belief
   :END:

Mon, 13 Dec 2010

In my experience over 90% of the arguments and criticisms made against Christianity can be answered with, "Yeah, I don't believe in a God like that either."---[[http://agentintellect.blogspot.com/2010/09/thought-of-day.html][Jim S.]]

** Hands
   :PROPERTIES:
   :CUSTOM_ID: hands
   :END:

Wed, 15 Dec 2010

I would fain be to the eternal God what a man's hand is to a man.---/Theologia Germanica/

** 2011
   :PROPERTIES:
   :CUSTOM_ID: section
   :END:

** Quotations
   :PROPERTIES:
   :CUSTOM_ID: quotations
   :END:

Sun, 09 Jan 2011

The problem with Internet quotations is that many are not genuine.---Abraham Lincoln

** Science
   :PROPERTIES:
   :CUSTOM_ID: science-1
   :END:

Thu, 23 Dec 2010

When everything is evidence of the thing you want to believe, it might be time to stop pretending you're all about /science/.---[[http://althouse.blogspot.com/2010/12/that-snow-outside-is-what-global.html][Ann Althouse]]
