* More Fieldstones 2015
  :PROPERTIES:
  :CUSTOM_ID: more-fieldstones-2015
  :END:

[[./index.html][Home]]

** Miracles
   :PROPERTIES:
   :CUSTOM_ID: miracles
   :END:

Tue, 17 Mar 2015 11:31:38

Emmet Fox challenges "believers" to accept that miracles are a necessary part of the gospel story, and likewise challenges "skeptics" to consider that they are a natural part of a universe that science doesn't fully comprehend.

#+BEGIN_HTML
  <h1 align="center">
#+END_HTML

Miracles

#+BEGIN_HTML
  </h1>
#+END_HTML

Now, one must extend every sympathy to the special pleadings of a man enthralled by the beauty and mystery of the Gospels, but who, in the absence of the Spiritual Key, seems to find his common sense and all the scientific knowledge of mankind flouted by much that these Gospels contain. But this simply will not do. If the miracles did not happen, the rest of the Gospel story loses all real significance. If Jesus did not believe them to be possible, and undertake to perform them---never, it is true, for the sake of display, but still constantly and repeatedly---if he did not believe and teach many things in flat contradiction to eighteenth-and nineteenth-century rationalistic philosophy, then the Gospel message is chaotic, contradictory, and devoid of all significance. We cannot ride away from the dilemma by saying that Jesus was not interested in the current beliefs and superstitions of his time; that he took them more or less for granted passively; because what really interested him was character. This is a feeble argument, because character must include both an intelligent and a vital all-round reaction to life. Character must include some definite beliefs and convictions concerning things that really matter.

But the miracles did happen. All the deeds related of Jesus in the four Gospels did happen, and many others too, "the which, if they should be written, every one, I suppose that even the world itself could not contain the books that should be written." Jesus himself justified what people thought to be a strange and wonderful teaching by the works he was able to do; and he went further and said, referring to those who study and practice his teaching: "The works that I do, ye shall do, and greater works."

Now what, after all, is a miracle? Those who deny the possibility of miracles on the ground that the universe is a perfect system of law and order, to the operation of which there can be no exceptions, are perfectly right. But the explanation is that the world of which we are normally aware, and with whose laws alone most people are acquainted, is only a fragment of the whole universe as it really is; and that there is such a thing as appealing from a lower to a higher law---from a lesser to a greater expression. Now the appeal from the lower to the higher law is not really a breach of law, for the possibility of such an appeal is part of the major constitution of the universe, and, therefore, in the sense of a real breach of law, miracles are impossible. Yet, in the sense that all the ordinary rules and limitations of the physical plane can be set aside or overridden by an understanding which has risen above them, miracles, in the colloquial sense of the word, can and do happen.

** Moral Authority
   :PROPERTIES:
   :CUSTOM_ID: moral-authority
   :END:

Thu, 24 Sep 2015

When I heard that Pope Francis had visited the Little Sisters of the Poor last night, I heard Martin Luther King's voice saying his words from Birmingham Jail: "One has not only a legal but a moral responsibility to obey just laws. Conversely, one has a moral responsibility to disobey unjust laws."

He deserves his propers for doing that.

** Paul and Orthodoxy
   :PROPERTIES:
   :CUSTOM_ID: paul-and-orthodoxy
   :END:

Sun, 13 Dec 2015

Reading Lietzmann's /A History of the Early Church/, it's tempting to think that due to accidents of timing, because Saul/Paul was a Hellenised Jew with a desire to reach others whose religious concerns were Hellenistic more than Jewish, and because he never heard Jesus speak in the flesh, the "Orthodox" or "Winning" interpretation of Christianity became more concerned with Hellenic mystery religion's issues and less with Jesus' teachings. Eh?
